/*
 * This file is generated by jOOQ.
 */
package com.idorasi.eligibility.entity;


import com.idorasi.eligibility.entity.tables.AuditLogs;
import com.idorasi.eligibility.entity.tables.EligibilityRecords;

import java.util.Arrays;
import java.util.List;

import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * standard public schema
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.audit_logs</code>.
     */
    public final AuditLogs AUDIT_LOGS = AuditLogs.AUDIT_LOGS;

    /**
     * The table <code>public.eligibility_records</code>.
     */
    public final EligibilityRecords ELIGIBILITY_RECORDS = EligibilityRecords.ELIGIBILITY_RECORDS;

    /**
     * No further instances allowed
     */
    private Public() {
        super(DSL.name("public"), null, DSL.comment("standard public schema"));
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AuditLogs.AUDIT_LOGS,
            EligibilityRecords.ELIGIBILITY_RECORDS
        );
    }
}
