/*
 * This file is generated by jOOQ.
 */
package com.idorasi.eligibility.entity;


import com.idorasi.eligibility.entity.tables.AuditLogs;
import com.idorasi.eligibility.entity.tables.EligibilityRecords;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.audit_logs</code>.
     */
    public static final AuditLogs AUDIT_LOGS = AuditLogs.AUDIT_LOGS;

    /**
     * The table <code>public.eligibility_records</code>.
     */
    public static final EligibilityRecords ELIGIBILITY_RECORDS = EligibilityRecords.ELIGIBILITY_RECORDS;
}
