/*
 * This file is generated by jOOQ.
 */
package com.idorasi.eligibility.entity.tables.records;


import com.idorasi.eligibility.entity.tables.EligibilityRecords;

import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EligibilityRecordsRecord extends UpdatableRecordImpl<EligibilityRecordsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.eligibility_records.member_unique_id</code>.
     */
    public void setMemberUniqueId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.eligibility_records.member_unique_id</code>.
     */
    public String getMemberUniqueId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.eligibility_records.first_name</code>.
     */
    public void setFirstName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.eligibility_records.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.eligibility_records.last_name</code>.
     */
    public void setLastName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.eligibility_records.last_name</code>.
     */
    public String getLastName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.eligibility_records.date_of_birth</code>.
     */
    public void setDateOfBirth(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.eligibility_records.date_of_birth</code>.
     */
    public LocalDate getDateOfBirth() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>public.eligibility_records.gender</code>.
     */
    public void setGender(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.eligibility_records.gender</code>.
     */
    public String getGender() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.eligibility_records.relations</code>.
     */
    public void setRelations(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.eligibility_records.relations</code>.
     */
    public String getRelations() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.eligibility_records.sub_group</code>.
     */
    public void setSubGroup(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.eligibility_records.sub_group</code>.
     */
    public String getSubGroup() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.eligibility_records.job_type</code>.
     */
    public void setJobType(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.eligibility_records.job_type</code>.
     */
    public String getJobType() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.eligibility_records.hire_date</code>.
     */
    public void setHireDate(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.eligibility_records.hire_date</code>.
     */
    public String getHireDate() {
        return (String) get(8);
    }

    /**
     * Setter for
     * <code>public.eligibility_records.eligibility_start_date</code>.
     */
    public void setEligibilityStartDate(LocalDate value) {
        set(9, value);
    }

    /**
     * Getter for
     * <code>public.eligibility_records.eligibility_start_date</code>.
     */
    public LocalDate getEligibilityStartDate() {
        return (LocalDate) get(9);
    }

    /**
     * Setter for <code>public.eligibility_records.eligibility_end_date</code>.
     */
    public void setEligibilityEndDate(LocalDate value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.eligibility_records.eligibility_end_date</code>.
     */
    public LocalDate getEligibilityEndDate() {
        return (LocalDate) get(10);
    }

    /**
     * Setter for <code>public.eligibility_records.employee_status</code>.
     */
    public void setEmployeeStatus(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.eligibility_records.employee_status</code>.
     */
    public String getEmployeeStatus() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.eligibility_records.phone_number</code>.
     */
    public void setPhoneNumber(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.eligibility_records.phone_number</code>.
     */
    public String getPhoneNumber() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.eligibility_records.address_1</code>.
     */
    public void setAddress_1(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.eligibility_records.address_1</code>.
     */
    public String getAddress_1() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.eligibility_records.address_2</code>.
     */
    public void setAddress_2(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.eligibility_records.address_2</code>.
     */
    public String getAddress_2() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.eligibility_records.city</code>.
     */
    public void setCity(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.eligibility_records.city</code>.
     */
    public String getCity() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.eligibility_records.state_code</code>.
     */
    public void setStateCode(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.eligibility_records.state_code</code>.
     */
    public String getStateCode() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.eligibility_records.zip_code</code>.
     */
    public void setZipCode(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.eligibility_records.zip_code</code>.
     */
    public String getZipCode() {
        return (String) get(17);
    }

    /**
     * Setter for <code>public.eligibility_records.country</code>.
     */
    public void setCountry(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.eligibility_records.country</code>.
     */
    public String getCountry() {
        return (String) get(18);
    }

    /**
     * Setter for <code>public.eligibility_records.employee_group</code>.
     */
    public void setEmployeeGroup(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.eligibility_records.employee_group</code>.
     */
    public String getEmployeeGroup() {
        return (String) get(19);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EligibilityRecordsRecord
     */
    public EligibilityRecordsRecord() {
        super(EligibilityRecords.ELIGIBILITY_RECORDS);
    }

    /**
     * Create a detached, initialised EligibilityRecordsRecord
     */
    public EligibilityRecordsRecord(String memberUniqueId, String firstName, String lastName, LocalDate dateOfBirth, String gender, String relations, String subGroup, String jobType, String hireDate, LocalDate eligibilityStartDate, LocalDate eligibilityEndDate, String employeeStatus, String phoneNumber, String address_1, String address_2, String city, String stateCode, String zipCode, String country, String employeeGroup) {
        super(EligibilityRecords.ELIGIBILITY_RECORDS);

        setMemberUniqueId(memberUniqueId);
        setFirstName(firstName);
        setLastName(lastName);
        setDateOfBirth(dateOfBirth);
        setGender(gender);
        setRelations(relations);
        setSubGroup(subGroup);
        setJobType(jobType);
        setHireDate(hireDate);
        setEligibilityStartDate(eligibilityStartDate);
        setEligibilityEndDate(eligibilityEndDate);
        setEmployeeStatus(employeeStatus);
        setPhoneNumber(phoneNumber);
        setAddress_1(address_1);
        setAddress_2(address_2);
        setCity(city);
        setStateCode(stateCode);
        setZipCode(zipCode);
        setCountry(country);
        setEmployeeGroup(employeeGroup);
    }
}
